# Generated by Django 4.1.10 on 2023-09-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_movies',
        ),
    ]
